config/routes.rb
Rails.application.routes.draw do
  resources :events
  get "/menu", to: "menu#index"
  get "/menu_user", to: "menu#user"
  get "/menu_role", to: "menu#role"
  get "/admin_edit", to: "admin#edit_role"
  get "/menu_event", to: "menu#event"
  get "/menu_attendance/:id", to: "menu#attendance", as: 'menu_attendance'
  get "/invite/:event_id", to: 'menu#invite', as: 'invite'
  post '/attendances/:user_id/events/:event_id', to: 'menu#create_attendance', as: 'create_attendance'
  post '/attendances/:user_id/events/:event_id/absent', to: 'menu#create_absent', as: 'create_absent'
  post 'invite/:user_id', to: 'menu#send_invitation', as: 'send_invite'
  root "menu#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do
    delete '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
    scope :present_status, ->(status) {where(status:status)}
end

app/models/event.rb
class Event < ApplicationRecord
    mount_uploader :photo, ImageUploader
    has_many :attendances
    has_many :invitations
end

app/models/invitation.rb
class Invitation < ApplicationRecord\
    belongs_to :user
    belongs_to :event
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_create :assign_default_role
  has_many :attendances
  has_many :invitations
  # after_create :send_new_user_notification
  
  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
  private

  def send_new_user_notification
    UserMailer.new_user_notification(self).deliver_now
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def edit_role
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :start_date, :end_date, :description, :photo)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  # before_action :set_attendance, only: []

  def index
  end

  def event
    @q = Event.order(:id).ransack(params[:q])
    @events = @q.result(distinct: true).page(params[:page]).per(5)

  end

  def user
    @q = User.order(id: :asc).ransack(params[:q])
    #@q = User.ransack(params[:q])
    @user = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def role
    @q = Role.order(id: :asc).ransack(params[:q])
    @role = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def attendance
    @q =  Attendance.includes(:user, :event).where(event_id:params[:id]).ransack(params[:q])
    @attendance = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def create_attendance
    att = Attendance.new(user_id:params[:user_id], event_id:params[:event_id], status:'Hadir')
    att.save
    redirect_to menu_event_path
  end

  def create_absent
    att = Attendance.new(user_id:params[:user_id], event_id:params[:event_id], status:'Absen')
    att.save
    redirect_to menu_event_path
  end

  def invite 
    @q = User.where.not(id: Attendance.where(event_id: params[:event_id]).pluck(:user_id)).ransack(params[:q])
    @users = @q.result.page(params[:page]).per(5)
  end

  def send_invitation
    user = User.find(params[:user_id])
    # InvitationMailer.send_invitation(user).deliver_now
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/edit_role.html.erb
<h1>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</h1>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>


<% if  current_user.roles.exists?(name: 'admin')%>
<h2>Event</h2>
<%= link_to 'New Event', new_event_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th>Photo</th>
      <th>Check Attendance</th>
      <th>Invite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.description %></td>
        <td><img class="w-50"src="<%= event.photo %>"></td>
        <td><%= link_to 'Check Attendant', menu_attendance_path(event.id) %></td>
        <td><%= link_to 'Invite', invite_path(event.id) %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% else %>
  <strong>Forbidden</strong>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @event.photo %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_navigation.html.erb
  <ul class="navbar">
    <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path %></li>
    <li class="<%= 'active' if current_page?(menu_user_path) %>"><%= link_to 'User', menu_user_path %></li>
    <li class="<%= 'active' if current_page?(menu_role_path) %>"><%= link_to 'Role', menu_role_path %></li>
    <li class="<%= 'active' if current_page?(menu_event_path) %>"><%= link_to 'Event', menu_event_path %></li>  
    <% if current_user.roles.exists?(name: 'admin') %>
      <li class="<%= 'active' if current_page?(events_path) %>"><%= link_to 'Edit Event', events_path %></li>
    <% end %>
    
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoterbTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>. With Roles <strong><%= current_user.roles.pluck(:name) %></strong>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <%= render 'layouts/navigation' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/menu/attendance.html.erb
<h2>List Attendance</h2>

<%= search_form_for @q, url: menu_attendance_path do |f| %>
  <%= f.label :search %>
  <%= f.search_field :user_full_name_or_user_email_or_event_name_cont %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', menu_event_path %>
<%= paginate @attendance %>

<table>
  <thead>
    <tr>
      <td><strong>event name</strong></td>
      <td><strong>user id</strong></td>
      <td><strong>email</strong></td>
      <td><strong>name</strong></td>
      <td><strong>status</strong></td>
    </tr>
  </thead>
  <tbody>
    <% @attendance.each do |a| %>
      <tr>
        
        <% if a.status == 'Hadir' %>
          <td><%= a.event.name %></td>
          <td><%= a.user_id %></td>
          <td><%= a.user.email %></td>
          <td><%= a.user.full_name %></td>
          <td><%= a.status %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/menu/event.html.erb
<h2>Menu Event</h2>

<%= search_form_for @q, url: menu_event_path do |f| %>
  <%= f.label :search %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>
<%= paginate @events %>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th>Photo</th>
      <th>status attendance</th>
      <th>Check Attendant</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.name %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.description %></td>
        <td><img class="w-50"src="<%= event.photo %>"></td>
        
        <td>
          
          <% if Attendance.find_by(user_id: current_user.id, event_id: event.id).present? %>
            Sudah Pilih
          <% else %>
            <%= button_to 'Hadir', create_attendance_path(user_id: current_user.id, event_id: event.id), method: :post %>
            <%= button_to 'Absen', create_absent_path(user_id: current_user.id, event_id: event.id), method: :post %>
          <% end %>
          
          
        </td>
        <td><%= link_to 'Check Attendant', menu_attendance_path(event.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @events %>

app/views/menu/index.html.erb
<p class="navbar-text pull-right">
  <% if current_user.roles.exists?(name: 'admin') %>
    <%= link_to "Edit Event", events_path%>
  <% end %>
</p>

<div class="field">
  <ul>
    <li><%= link_to 'list user', menu_user_path%></li>
    <li><%= link_to 'list role', menu_role_path%> </li>
  </ul>
</div>

app/views/menu/invite.html.erb
<h2>Invite</h2>

  <%= search_form_for @q, url: invite_path do |f| %>
    <%= f.label :search %>
    <%= f.search_field :full_name_or_email_cont %>
    <%= f.submit %>
  <% end %>

<%= link_to 'Back', events_path, method: :get %>
<%= paginate @users %> 

<table>
  <thead>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Email</strong></td>
      <td><strong>Send Invitation</strong></td>
    </tr>
  </thead>
<tbody>
  
  <% @users.each do |u| %>
    <tr>
      <td><%= u.full_name %></td>
      <td><%= u.email %></td>
      <td><%= button_to 'Kirim Undangan', send_invite_path(u.id), data: { confirm: 'Are you sure you want to proceed?' } %></button></td>
    </tr>
  <% end %>
  
</tbody>
</table>

app/views/menu/role.html.erb
<h2> Menu Role List</h2>

<%= search_form_for @q, url: menu_role_path do |f| %>
  <%= f.label :search %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>
<table>
  <thead>
      <tr>
        <td><strong>id</strong></td>
        <td><strong>role</strong></td>
        <td><strong>description</strong></td>
      </tr>
  </thead>
  <tbody>
    <% @role.each do |r| %>
      <tr>
        <td><%= r.id %></td>
        <td><%= r.name %></td>
        <td><%= r.description %></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<%= link_to 'back', menu_path %>

app/views/menu/user.html.erb
<h2> Menu User List</h2>

<%= search_form_for @q, url: menu_user_path do |f| %>
  <%= f.label :search %>
  <%= f.search_field :full_name_or_email_cont %>
  <%= f.submit %>
<% end %>
<br>
<%= paginate @user %>
<table>
  <thead>
      <tr>
        <td><strong>id</strong></td>
        <td><strong>full_name</strong></td>
        <td><strong>email</strong></td>
        <td><strong>role</strong></td>
      </tr>
  </thead>
  <tbody>
    <% @user.each do |u| %>
      <tr>
        <td><%= u.id %></td>
        <td><%= u.full_name %></td>
        <td><%= u.email %></td>
        <td><%= u.roles.pluck(:name) %></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<%= link_to 'back', menu_path %>


  